#s3proxy config file
s3proxy: default
server:
  addr: :80
  tls:
    key:
    cert:
  timeouts:
    read: 3s
    write: 15s
    idle: 10s
  headers:
    cors: "*"
    cache: no-store
source:
  bucket: bucket
  host: example
  id: id
  key: key
public-keys:
# - AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
cache:
  dir: /tmp/s3proxy
  #in GB
  size: 0