name: Build Proxy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build Go Project
        run: go build -o s3proxy

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-artifacts
          path: s3proxy
